/**
 * Documentation Generator Service
 * Generates comprehensive metamodel documentation
 */

import type { LProject, LClass, LAttribute, LReference } from '../joiner';

export interface DocumentationOptions {
    format: 'markdown' | 'html';
    includeAbstractSyntax: boolean;
    includeConcreteSyntax: boolean;
    includeConstraints: boolean;
    includeExamples: boolean;
}

export class DocumentationGenerator {
    /**
     * Generate complete metamodel documentation
     */
    static generate(
        project: LProject,
        options: DocumentationOptions = {
            format: 'markdown',
            includeAbstractSyntax: true,
            includeConcreteSyntax: true,
            includeConstraints: true,
            includeExamples: true,
        }
    ): string {
        const sections: string[] = [];
        const projectName = project.name || 'Untitled Project';

        // Title
        sections.push(`# ${projectName} - Language Documentation`);
        sections.push('');
        sections.push(`Generated on ${new Date().toLocaleDateString()}`);
        sections.push('');
        sections.push('---');
        sections.push('');

        // Overview
        sections.push('## Overview');
        sections.push('');
        sections.push(`This document describes the **${projectName}** modeling language.`);
        sections.push('');

        // Statistics
        const stats = this.getStatistics(project);
        sections.push('### Statistics');
        sections.push('');
        sections.push(`- **Metaclasses**: ${stats.metaclasses}`);
        sections.push(`- **Attributes**: ${stats.attributes}`);
        sections.push(`- **References**: ${stats.references}`);
        sections.push(`- **Enumerations**: ${stats.enumerations}`);
        sections.push('');
        sections.push('---');
        sections.push('');

        // Abstract Syntax
        if (options.includeAbstractSyntax) {
            sections.push(this.generateAbstractSyntax(project));
            sections.push('');
            sections.push('---');
            sections.push('');
        }

        // Concrete Syntax
        if (options.includeConcreteSyntax) {
            sections.push(this.generateConcreteSyntax(project));
            sections.push('');
            sections.push('---');
            sections.push('');
        }

        // Constraints
        if (options.includeConstraints) {
            sections.push(this.generateConstraints(project));
            sections.push('');
            sections.push('---');
            sections.push('');
        }

        // Examples
        if (options.includeExamples) {
            sections.push(this.generateExamples(project));
            sections.push('');
        }

        // Footer
        sections.push('---');
        sections.push('');
        sections.push('*Generated by Jjodie - AI Metamodeling Assistant*');

        return sections.join('\n');
    }

    /**
     * Get metamodel statistics
     */
    private static getStatistics(project: LProject) {
        const classes = project.classes || [];
        const metaclasses = classes.length;

        const attributes = classes.reduce(
            (sum: number, cls: LClass) => sum + (cls.attributes?.length || 0),
            0
        );

        const references = classes.reduce(
            (sum: number, cls: LClass) => sum + (cls.references?.length || 0),
            0
        );

        // Count enumerations if available
        const enumerations = (project as any).enumerations?.length || 0;

        return { metaclasses, attributes, references, enumerations };
    }

    /**
     * Generate Abstract Syntax section
     */
    private static generateAbstractSyntax(project: LProject): string {
        const lines: string[] = [];

        lines.push('## Abstract Syntax');
        lines.push('');
        lines.push('The abstract syntax defines the concepts (metaclasses) and their relationships.');
        lines.push('');

        const classes = project.classes || [];

        if (classes.length === 0) {
            lines.push('*No metaclasses defined yet.*');
            return lines.join('\n');
        }

        // Find root classes (no superclass)
        const rootClasses = classes.filter((c: LClass) => {
            const extendsIds = (c as any).extends;
            return !extendsIds || extendsIds.length === 0;
        });

        // Generate documentation for each root class and its descendants
        rootClasses.forEach((cls: LClass) => {
            lines.push(this.generateClassDocumentation(cls, project, 0));
            lines.push('');
        });

        return lines.join('\n');
    }

    /**
     * Generate documentation for a single class
     */
    private static generateClassDocumentation(
        cls: LClass,
        project: LProject,
        level: number
    ): string {
        const lines: string[] = [];
        const headerLevel = Math.min(level + 3, 6); // h3 to h6
        const header = '#'.repeat(headerLevel);

        // Class header
        const isAbstract = (cls as any).abstract || (cls as any).isAbstract;
        const abstractLabel = isAbstract ? ' *(abstract)*' : '';
        lines.push(`${header} ${cls.name}${abstractLabel}`);
        lines.push('');

        // Superclass info
        const extendsIds = (cls as any).extends;
        if (extendsIds && extendsIds.length > 0) {
            const superclasses = extendsIds
                .map((id: string) => {
                    const superCls = project.classes?.find((c: LClass) => c.id === id);
                    return superCls?.name || 'Unknown';
                })
                .filter((name: string) => name !== 'Unknown');

            if (superclasses.length > 0) {
                lines.push(`*Extends: ${superclasses.join(', ')}*`);
                lines.push('');
            }
        }

        // Attributes
        const attributes = cls.attributes || [];
        if (attributes.length > 0) {
            lines.push('**Attributes:**');
            lines.push('');
            lines.push('| Name | Type | Multiplicity |');
            lines.push('|------|------|--------------|');

            attributes.forEach((attr: LAttribute) => {
                const type = (attr as any).type || 'String';
                const lower = (attr as any).lowerBound ?? 0;
                const upper = (attr as any).upperBound ?? 1;
                const mult = this.formatMultiplicity(lower, upper);
                lines.push(`| \`${attr.name}\` | ${type} | ${mult} |`);
            });

            lines.push('');
        }

        // References
        const references = cls.references || [];
        if (references.length > 0) {
            lines.push('**References:**');
            lines.push('');
            lines.push('| Name | Target | Type | Multiplicity |');
            lines.push('|------|--------|------|--------------|');

            references.forEach((ref: LReference) => {
                const targetId = (ref as any).type;
                const target = project.classes?.find((c: LClass) => c.id === targetId);
                const targetName = target?.name || 'Unknown';
                const containment = (ref as any).containment;
                const refType = containment ? 'Composition' : 'Association';
                const lower = (ref as any).lowerBound ?? 0;
                const upper = (ref as any).upperBound ?? 1;
                const mult = this.formatMultiplicity(lower, upper);
                lines.push(`| \`${ref.name}\` | ${targetName} | ${refType} | ${mult} |`);
            });

            lines.push('');
        }

        // No attributes or references
        if (attributes.length === 0 && references.length === 0) {
            lines.push('*No attributes or references defined.*');
            lines.push('');
        }

        // Find and document subclasses
        const subclasses = (project.classes || []).filter((c: LClass) => {
            const extendsIds = (c as any).extends;
            return extendsIds && extendsIds.includes(cls.id);
        });

        if (subclasses.length > 0) {
            lines.push('**Subclasses:**');
            lines.push('');
            subclasses.forEach((sub: LClass) => {
                lines.push(this.generateClassDocumentation(sub, project, level + 1));
            });
        }

        return lines.join('\n');
    }

    /**
     * Format multiplicity bounds
     */
    private static formatMultiplicity(lower: number, upper: number): string {
        if (lower === upper) {
            return `[${lower}]`;
        }
        if (upper === -1 || upper === Infinity) {
            return `[${lower}..*]`;
        }
        return `[${lower}..${upper}]`;
    }

    /**
     * Generate Concrete Syntax section
     */
    private static generateConcreteSyntax(project: LProject): string {
        const lines: string[] = [];

        lines.push('## Concrete Syntax');
        lines.push('');
        lines.push('The concrete syntax defines the visual notation for each concept.');
        lines.push('');

        // Check for notation/shapes
        const notation = (project as any).notation || (project as any).shapes;
        const classes = project.classes || [];

        if (!notation || Object.keys(notation).length === 0) {
            lines.push('*Visual notation not yet defined.*');
            lines.push('');
            lines.push('To define concrete syntax:');
            lines.push('1. Select a metaclass in the editor');
            lines.push('2. Open the Shape/Notation panel');
            lines.push('3. Configure shape, color, and icons');
            return lines.join('\n');
        }

        lines.push('| Metaclass | Shape | Color | Icon |');
        lines.push('|-----------|-------|-------|------|');

        classes.forEach((cls: LClass) => {
            const classNotation = notation[cls.name] || notation[cls.id] || {};
            const shape = classNotation.shape || 'Rectangle';
            const color = classNotation.color || 'Default';
            const icon = classNotation.icon || '-';
            lines.push(`| ${cls.name} | ${shape} | ${color} | ${icon} |`);
        });

        return lines.join('\n');
    }

    /**
     * Generate Constraints section
     */
    private static generateConstraints(project: LProject): string {
        const lines: string[] = [];

        lines.push('## Static Semantics (Constraints)');
        lines.push('');
        lines.push('Well-formedness rules that models must satisfy.');
        lines.push('');

        const classes = project.classes || [];
        let hasConstraints = false;

        classes.forEach((cls: LClass) => {
            const constraints = (cls as any).constraints || [];
            if (constraints.length > 0) {
                hasConstraints = true;

                lines.push(`### ${cls.name}`);
                lines.push('');

                constraints.forEach((constraint: any, idx: number) => {
                    const name = constraint.name || `Constraint ${idx + 1}`;
                    lines.push(`**${name}**`);
                    lines.push('');

                    if (constraint.description || constraint.message) {
                        lines.push(constraint.description || constraint.message);
                        lines.push('');
                    }

                    if (constraint.expression || constraint.body) {
                        lines.push('```ocl');
                        lines.push(`context ${cls.name}`);
                        lines.push(`inv ${name}: ${constraint.expression || constraint.body}`);
                        lines.push('```');
                        lines.push('');
                    }
                });
            }
        });

        if (!hasConstraints) {
            lines.push('*No constraints defined yet.*');
            lines.push('');
            lines.push('Constraints help enforce:');
            lines.push('- Business rules');
            lines.push('- Data integrity');
            lines.push('- Structural invariants');
            lines.push('');
            lines.push('Example constraint (OCL):');
            lines.push('```ocl');
            lines.push('context Vehicle');
            lines.push('inv validYear: self.year >= 1886 and self.year <= 2025');
            lines.push('```');
        }

        return lines.join('\n');
    }

    /**
     * Generate Examples section
     */
    private static generateExamples(project: LProject): string {
        const lines: string[] = [];

        lines.push('## Examples');
        lines.push('');

        const examples = (project as any).examples || [];

        if (examples.length === 0) {
            lines.push('*No examples provided yet.*');
            lines.push('');
            lines.push('Examples help users understand how to create valid models.');
            lines.push('Consider adding:');
            lines.push('- Simple instance diagrams');
            lines.push('- Common usage patterns');
            lines.push('- Edge cases and variations');
            return lines.join('\n');
        }

        examples.forEach((example: any, idx: number) => {
            lines.push(`### Example ${idx + 1}: ${example.title || 'Untitled'}`);
            lines.push('');

            if (example.description) {
                lines.push(example.description);
                lines.push('');
            }

            if (example.code || example.content) {
                lines.push('```');
                lines.push(example.code || example.content);
                lines.push('```');
                lines.push('');
            }
        });

        return lines.join('\n');
    }

    /**
     * Download documentation as file
     */
    static download(content: string, filename: string): void {
        const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
        const url = URL.createObjectURL(blob);

        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);

        URL.revokeObjectURL(url);
    }
}

export default DocumentationGenerator;
