/**
 * AI Disclaimer Component
 * Displays a disclaimer for AI-generated content across the application
 *
 * Used in:
 * - Jodie Chat
 * - ScriptBlocks (code generated by AI)
 * - Documentation Generation
 * - Mapping Discovery (AI-suggested mappings)
 */

import React from 'react';
import {AI, AIProvider, JodieConfig} from '../../types/jodie';
import './AIDisclaimer.scss';

interface AIDisclaimerProps {
    /** Compact mode: single line, smaller text. Use inside tight spaces like code blocks */
    compact?: boolean;
}

/**
 * Disclaimer shown wherever AI-generated content appears.
 * Automatically reads the current provider name from settings.
 */
export const AIDisclaimer: React.FC<AIDisclaimerProps> = ({ compact = false }) => {
    const llm = AI[JodieConfig.current.activeProvider];

    if (compact) {
        return (
            <span className="ai-disclaimer ai-disclaimer--compact">
                <i className="bi bi-info-circle" />
                {llm.name} can make mistakes. Verify important information.
            </span>
        );
    }

    return (
        <div className="ai-disclaimer">
            <i className="bi bi-info-circle" />
            <span>
                Jjodel uses {llm.name} and can make mistakes. Verify important information.
            </span>
        </div>
    );
};

export default AIDisclaimer;
