/**
 * MegamodelNode — Rich card node for the Megamodel diagram.
 *
 * Three-zone layout: header (badge + name), body (stat pills),
 * footer (status dot + label). Draggable via mousedown on the card.
 * Supports right-click context menu and inline rename (F2).
 */

import React, { useCallback, useRef, useState, useEffect } from 'react';
import type { MmNodeKind, MmNodeStats, MmNodeStatus } from './MegamodelEdge';

export interface MegamodelNodeProps {
    id: string;
    kind: MmNodeKind;
    badgeLabel: string;
    name: string;
    typeLabel: string;
    x: number;
    y: number;
    stats: MmNodeStats;
    status: MmNodeStatus;
    /** True if this model was generated by a transformation */
    generated?: boolean;
    /** Human-readable generation info (e.g. "Generated 2m ago by MyTransform") */
    generatedLabel?: string;
    selected?: boolean;
    isRenaming?: boolean;
    onMouseDown: (e: React.MouseEvent, nodeId: string) => void;
    onDoubleClick?: (nodeId: string) => void;
    onContextMenu?: (e: React.MouseEvent, nodeId: string) => void;
    onRename?: (nodeId: string, newName: string) => void;
}

// ─── Stat pills per node kind ───────────────────────────────────────────────

function getStatPills(kind: MmNodeKind, stats: MmNodeStats): Array<{ value: number; label: string }> {
    const pills: Array<{ value: number; label: string }> = [];
    if (kind === 'metamodel') {
        if (stats.classCount != null) pills.push({ value: stats.classCount, label: 'classes' });
        if (stats.referenceCount != null) pills.push({ value: stats.referenceCount, label: 'refs' });
        if (stats.attributeCount != null) pills.push({ value: stats.attributeCount, label: 'attrs' });
    } else if (kind === 'model') {
        if (stats.objectCount != null) pills.push({ value: stats.objectCount, label: 'objects' });
        if (stats.linkCount != null) pills.push({ value: stats.linkCount, label: 'links' });
    } else if (kind === 'transformation') {
        if (stats.ruleCount != null) pills.push({ value: stats.ruleCount, label: 'rules' });
        if (stats.mappingCount != null) pills.push({ value: stats.mappingCount, label: 'mappings' });
    }
    return pills;
}

// ─── Transform icon SVG ─────────────────────────────────────────────────────

const TransformIcon: React.FC = () => (
    <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
        <path d="M2 5h4l2-3h4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
        <path d="M2 9h4l2 3h4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
);

// ─── Component ──────────────────────────────────────────────────────────────

const MegamodelNode: React.FC<MegamodelNodeProps> = ({
    id, kind, badgeLabel, name, typeLabel, x, y, stats, status,
    generated, generatedLabel, selected, isRenaming,
    onMouseDown, onDoubleClick, onContextMenu, onRename,
}) => {
    const badgeClass = generated ? 'mm-card__badge--generated' : `mm-card__badge--${kind}`;
    const cardRef = useRef<HTMLDivElement>(null);
    const inputRef = useRef<HTMLInputElement>(null);
    const pills = getStatPills(kind, stats);
    const hasProgress = kind === 'transformation' && stats.completionPercent != null;

    // Inline rename state
    const [editName, setEditName] = useState(name);

    useEffect(() => {
        if (isRenaming) {
            setEditName(name);
            // Focus after render
            requestAnimationFrame(() => {
                inputRef.current?.focus();
                inputRef.current?.select();
            });
        }
    }, [isRenaming, name]);

    const commitRename = useCallback(() => {
        const trimmed = editName.trim();
        if (trimmed && trimmed !== name) {
            onRename?.(id, trimmed);
        } else {
            // Always signal done to exit rename mode, even if name unchanged
            onRename?.(id, name);
        }
    }, [editName, name, id, onRename]);

    const handleDoubleClick = useCallback((e: React.MouseEvent) => {
        e.stopPropagation();
        if (!onDoubleClick || isRenaming) return;
        // Flash highlight before opening
        const el = cardRef.current;
        if (el) {
            el.classList.add('mm-card--opening');
            setTimeout(() => onDoubleClick(id), 150);
        } else {
            onDoubleClick(id);
        }
    }, [onDoubleClick, id, isRenaming]);

    const handleContextMenu = useCallback((e: React.MouseEvent) => {
        e.preventDefault();
        e.stopPropagation();
        onContextMenu?.(e, id);
    }, [onContextMenu, id]);

    return (
        <div
            ref={cardRef}
            className={`mm-card mm-card--${kind}${selected ? ' mm-card--selected' : ''}`}
            style={{ left: x, top: y }}
            onMouseDown={(e) => onMouseDown(e, id)}
            onDoubleClick={handleDoubleClick}
            onContextMenu={handleContextMenu}
            title={onDoubleClick && !isRenaming ? `Double-click to open ${name}` : undefined}
        >
            {/* Header */}
            <div className="mm-card__header">
                <div className={`mm-card__badge ${badgeClass}`}>
                    {kind === 'transformation' ? <TransformIcon /> : badgeLabel}
                </div>
                <div className="mm-card__info">
                    <div className="mm-card__name" title={isRenaming ? undefined : name}>
                        {isRenaming ? (
                            <input
                                ref={inputRef}
                                className="mm-card__name-input"
                                value={editName}
                                onChange={(e) => setEditName(e.target.value)}
                                onKeyDown={(e) => {
                                    e.stopPropagation();
                                    if (e.key === 'Enter') {
                                        e.preventDefault();
                                        commitRename();
                                    }
                                    if (e.key === 'Escape') {
                                        e.preventDefault();
                                        setEditName(name);
                                        onRename?.(id, name); // signal cancel (no change)
                                    }
                                }}
                                onBlur={commitRename}
                                onMouseDown={(e) => e.stopPropagation()} // prevent drag
                            />
                        ) : (
                            <span>{name}</span>
                        )}
                    </div>
                    <div className="mm-card__type">
                        {typeLabel}
                        {generated && <span className="mm-card__generated-pill">generated</span>}
                    </div>
                </div>
            </div>

            {/* Body */}
            <div className="mm-card__body">
                {pills.length > 0 && (
                    <div className="mm-card__stats">
                        {pills.map((p, i) => (
                            <div key={i} className="mm-card__pill">
                                <span className="mm-card__pill-value">{p.value}</span>
                                {' '}{p.label}
                            </div>
                        ))}
                    </div>
                )}
                {hasProgress && (
                    <div className="mm-card__progress">
                        <div className="mm-card__progress-track">
                            <div
                                className="mm-card__progress-fill"
                                style={{ width: `${stats.completionPercent}%` }}
                            />
                        </div>
                        <span className="mm-card__progress-label">
                            {stats.completionPercent}%
                        </span>
                    </div>
                )}
            </div>

            {/* Footer */}
            <div className="mm-card__footer">
                <div className={`mm-card__dot mm-card__dot--${generated ? 'info' : status.type}`} />
                <span className="mm-card__status">
                    {generated && generatedLabel ? generatedLabel : status.label}
                </span>
            </div>
        </div>
    );
};

export default React.memo(MegamodelNode);
