/**
 * The M2 name-uniqueness gate for a JjScript `create` — the pure half.
 *
 * JjScript's creators write with `D*.new` directly, which R-M2U-4 calls «the loading door»:
 * deliberately ungated, because it reproduces a state instead of proposing one. A `create`
 * typed by a user, or generated by Jjodie, is a PROPOSAL, and the gate for those lives where
 * the gesture arrives — on the L primitives for the canvas, and here for the script.
 *
 * So this module does NOT hold a rule. The rule is `checkM2NameUniqueness`
 * (`model/logicWrapper/nameUniqueness.ts`), the same verdict the L creators consult through
 * `m2CreateRefused` and the same one `commands/rename.ts` consults. What lives here is the
 * translation between JjScript's vocabulary and that verdict's: which namespace an
 * `elementType` belongs to, and what an `ExecutionResult` looks like when the verdict refuses.
 *
 * Why a module of its own rather than a block inside `create.ts`: neither `create.ts` nor
 * `nameUniqueness.ts` imports under node (the `joiner` barrel pulls monaco, and node refuses
 * its `.css`), so logic left in `create.ts` could only be tested by reading its source, which
 * CLAUDE.md §5 forbids. Everything below imports TYPES only, so the bench executes the subject.
 * `frontend/src/model/nameLookup.ts` is the worked example this follows.
 */

import type { M2NamespaceKind, UniquenessVerdict } from '../../model/logicWrapper/nameUniqueness';
import type { ExecutionResult } from '../types';

/**
 * The namespace each `create <elementType>` writes into.
 *
 * Every entry is the kind the L-layer twin already passes for the same write, so the script
 * and the canvas cannot disagree about the scope of a name:
 *
 *   classifier  LPackage.addClass / addEnumerator   (LModelElement.tsx:1952, :1963)
 *   package     LPackage.addPackage / LModel.addPackage  (:1940, :5182)
 *   feature     LClass.addAttribute / addReference / addOperation  (:3262, :3281, :3289)
 *   parameter   LOperation.addParameter             (:2468)
 *   literal     LEnumerator.addLiteral              (:4860)
 *
 * `instance` is absent on purpose: it is M1, governed by R-S1-*, and leaves `executeCreate`
 * before this gate. `datatype` is absent because JjScript has no command that creates one.
 */
export const M2_KIND_BY_ELEMENT_TYPE: { [elementType: string]: M2NamespaceKind } = {
    'class':          'classifier',
    'abstract class': 'classifier',
    'interface':      'classifier',
    'enum':           'classifier',
    'enumeration':    'classifier',
    'package':        'package',
    'attribute':      'feature',
    'reference':      'feature',
    'containment':    'feature',
    'composition':    'feature',
    'operation':      'feature',
    'parameter':      'parameter',
    'literal':        'literal',
};

/**
 * The namespace this `elementType` writes into, or `null` when it writes no M2 named element.
 *
 * `null` is the signal to skip the gate entirely and behave exactly as before — the same
 * convention `m2KindOf` uses for a className that is not an M2 named element. It must never
 * be read as «no rule applies to this name».
 */
export function m2KindForElementType(elementType: string | undefined | null): M2NamespaceKind | null {
    if (!elementType) return null;
    return M2_KIND_BY_ELEMENT_TYPE[elementType] ?? null;
}

/**
 * The refusal an accepted verdict does not produce.
 *
 * Returns `null` when the create may go ahead — which includes an accepted verdict carrying a
 * near-homonym `warning`, because R-M2U-1 makes that name legal. The caller is responsible for
 * carrying the warning into `ExecutionResult.warnings`: a refusal never has one, and an
 * acceptance that drops it would make the write silent, which is the half of R-M2U-1 that says
 * the near-collision is ANNOUNCED.
 *
 * The sentence is composed here rather than in `nameUniqueness.ts` so the shared
 * `refusalReason` stays the prefix every consumer prints verbatim. What JjScript adds around it
 * is the command's own vocabulary — the element type the user typed — and the metamodel, which
 * matters because R-M2U-2 makes the pool metamodel-wide and the same name in another metamodel
 * is legal: naming it is the difference between «this name is taken» and «this name is taken
 * HERE».
 *
 * `DUPLICATE_NAME` is in `KNOWN_ERROR_CODES` (`errors.ts`), so `errorFromResult` keeps it
 * instead of collapsing it to `OPERATION_FAILED`, and its table entry is `skippable: true` —
 * Skip Line is offered, which is what makes a re-run over an existing metamodel survivable.
 * No `suggestion` is set: the table's own («Use a different name or delete the existing element
 * first.») is the right one, and `errorFromResult` falls back to it.
 */
export function duplicateNameRefusal(
    elementType: string,
    name: string | undefined,
    verdict: UniquenessVerdict | undefined | null,
    metamodelName?: string
): ExecutionResult | null {
    if (!verdict || verdict.ok !== false) return null;
    const where = metamodelName ? ` (metamodel '${metamodelName}')` : '';
    const message = `Cannot create ${elementType} '${name}': ${verdict.reason}${where}.`;
    return {
        success: false,
        command: 'create',
        message,
        errors: [{ code: 'DUPLICATE_NAME', message }],
    };
}

/**
 * `warnings` with the verdict's near-homonym appended, or the list unchanged.
 *
 * Kept next to the refusal so the two halves of R-M2U-1 — refuse the collision, announce the
 * near-collision — are read in one place, and so a create that already carries warnings of its
 * own does not lose them.
 */
export function withNearHomonymWarning(
    warnings: string[] | undefined,
    verdict: UniquenessVerdict | undefined | null
): string[] | undefined {
    if (!verdict || verdict.ok === false || !verdict.warning) return warnings;
    return [...(warnings ?? []), verdict.warning];
}
